add quick-start guide
purenix-org/purenix pull request #38
Opened 2021-12-31 08:49 UTC by cdepillabout

This PR adds a quick-start guide.

The contents of this guide are taken from <https://discourse.nixos.org/t/purenix-nix-backend-for-purescript/15756/3>.

2022-01-01 08:10 UTC, jonascarpay requested changes
I like to format markdown files with one sentence per line, since it gives nice diffs and easy sentence reordering. Do you prefer this way?

2022-01-01 08:10 UTC, jonascarpay commented on docs/quick-start.md
> +Here's a quick-start guide for playing around with PureNix.
```suggestion
Here's a quick-start guide for seting up a PureNix project.
```

2022-01-01 08:10 UTC, jonascarpay commented on docs/quick-start.md
> +This creates a few files.  You'll need to edit some of these files in order to
```suggestion
This creates a template project.  You'll need to edit some of these files in order to
```

2022-01-02 09:08 UTC, cdepillabout commented
> I think it makes sense to add a link to the README in this PR.

Good idea, I did this in b6ccae3.

> More generally, I like to format markdown files with one sentence per line, since it gives nice diffs and easy sentence reordering. Do you prefer this way?

I've generally just been keeping to 80-characters per line, but I don't really have a strong feeling about this.

Nice diffs are of course nice though, so I'll switch to one sentence per line.  I made this change in 71a3de4.

2022-01-02 13:19 UTC, cdepillabout commented on docs/quick-start.md
> +actual package set.
Thanks for pointing this out.

I added another section that tries to clarify how package sets work, and what an end-user needs to be aware of with the PureNix package set: 2e952c3

2022-01-04 08:09 UTC, cdepillabout commented
I'll go ahead and merge this in, but @jonascarpay if there's anything else you'd like me to change, let me know and I can send a follow-up PR.

2022-01-04 08:09 UTC, merged

2022-01-04 08:10 UTC, jonascarpay commented
@cdepillabout Oh, were you waiting for a re-review? Sorry, this looks good, thanks!